#!/usr/bin/env python3
"""Regenerate the portable Comic Neue Bold ASCII atlases used by Canvas.

Source font: Comic Neue, commit ef5be72411141d01f0b865df8edb47e552c11c3c
Expected SHA-256 values:
ComicNeue-Bold.ttf:
    3e7e5fccfd7e0788f317b43312151c1bd5cf058c9697a8d83eac3939050bd61e
ComicNeue-BoldItalic.ttf:
    5c312c2a2fa64eee82f3b87fcfab8f3b12a5e59b043124401d322eb323cfbf16
"""

from __future__ import annotations

import hashlib
import pathlib
import sys

from PIL import Image, ImageDraw, ImageFont


EXPECTED_BOLD_SHA256 = "3e7e5fccfd7e0788f317b43312151c1bd5cf058c9697a8d83eac3939050bd61e"
EXPECTED_BOLD_ITALIC_SHA256 = "5c312c2a2fa64eee82f3b87fcfab8f3b12a5e59b043124401d322eb323cfbf16"
EXPECTED_BOLD_DATA_SHA256 = "437a505ab8d21363773f5c25c880562b3e2675780f1e5eafc8bd1204086d7507"
EXPECTED_BOLD_ZIG_SHA256 = "2417feb4f5ddb01085b143b2cf20ffd46a33309e10fa0664aa73b5c9eef62e66"
EXPECTED_ITALIC_DATA_SHA256 = "c32558edf1c6ceb2f65231ca57b729fc276843473e2f4b7d4ae514ff9b5bc174"
EXPECTED_ITALIC_ZIG_SHA256 = "223660da0176c00cf4fbff800a1581cc8a1e4b17463a9b10004ed1c892f9c38c"
FIRST = 0x20
COUNT = 95
SIZE = 20


def generate(
    source: pathlib.Path,
    expected_sha256: str,
    data_name: str,
    description: str,
) -> tuple[bytes, str]:
    actual_sha256 = hashlib.sha256(source.read_bytes()).hexdigest()
    if actual_sha256 != expected_sha256:
        raise SystemExit(
            f"{source.name} SHA-256 does not match the pinned Comic Neue source "
            f"(expected {expected_sha256}, found {actual_sha256})"
        )
    font = ImageFont.truetype(source, SIZE)
    ascent, descent = font.getmetrics()
    # Pillow exposes the same face metrics used to rasterize the checked-in
    # atlas.  Keep the nominal request size separate from the resulting text
    # metric height: Comic Neue's 20px request has an 18px ascent plus a 5px
    # descent.  The renderer needs both values to reproduce CFontInfo rather
    # than treating the 23px tmHeight as the LOGFONT request height.
    line_height = font.font.height
    external_leading = line_height - ascent - descent
    coverage = bytearray()
    records: list[tuple[int, int, int, int, int, int]] = []

    for codepoint in range(FIRST, FIRST + COUNT):
        character = chr(codepoint)
        left, top, right, bottom = font.getbbox(character)
        width = max(0, right - left)
        height = max(0, bottom - top)
        offset = len(coverage)
        if width and height:
            image = Image.new("L", (width, height), 0)
            ImageDraw.Draw(image).text((-left, -top), character, font=font, fill=255)
            coverage.extend(image.tobytes())
        advance = round(font.getlength(character))
        records.append((advance, width, height, left, top, offset))

    rows = "\n".join(
        f"    .{{ .advance = {advance}, .w = {width}, .h = {height}, "
        f".xoff = {xoff}, .yoff = {yoff}, .off = {offset} }},"
        for advance, width, height, xoff, yoff, offset in records
    )
    zig_source = (
        f"//! Antialiased proportional Comic Neue {description} atlas. Generated by\n"
        "//! `tools/generate_font.py` from the pinned SIL-OFL font described in\n"
        "//! `src/render/COMIC_NEUE_LICENSE.txt`.\n\n"
        "pub const first: u8 = 0x20;\n"
        f"pub const count: usize = {COUNT};\n"
        f"pub const request_size: i32 = {SIZE};\n"
        f"pub const ascent: i32 = {ascent};\n"
        f"pub const descent: i32 = {descent};\n"
        f"pub const external_leading: i32 = {external_leading};\n"
        f"pub const line_height: i32 = {line_height};\n\n"
        "pub const Glyph = struct { advance: u8, w: u8, h: u8, xoff: i8, yoff: i8, off: u32 };\n\n"
        f"pub const glyphs = [count]Glyph{{\n{rows}\n}};\n\n"
        f'pub const coverage = @embedFile("{data_name}");\n'
    )
    return bytes(coverage), zig_source


def verify_generated(label: str, data: bytes, zig_source: str, expected_data: str, expected_zig: str) -> None:
    data_sha256 = hashlib.sha256(data).hexdigest()
    zig_sha256 = hashlib.sha256(zig_source.encode("utf-8")).hexdigest()
    if data_sha256 != expected_data or zig_sha256 != expected_zig:
        raise SystemExit(
            f"{label} rasterizer output does not match the pinned atlas "
            f"(data {data_sha256}, Zig {zig_sha256}); use the documented "
            "Pillow/FreeType toolchain"
        )


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit(
            "usage: generate_font.py /path/to/ComicNeue-Bold.ttf "
            "/path/to/ComicNeue-BoldItalic.ttf"
        )
    bold_data, bold_zig = generate(
        pathlib.Path(sys.argv[1]),
        EXPECTED_BOLD_SHA256,
        "fontdata.bin",
        "Bold",
    )
    italic_data, italic_zig = generate(
        pathlib.Path(sys.argv[2]),
        EXPECTED_BOLD_ITALIC_SHA256,
        "fontdata_italic.bin",
        "Bold Italic",
    )
    verify_generated("Bold", bold_data, bold_zig, EXPECTED_BOLD_DATA_SHA256, EXPECTED_BOLD_ZIG_SHA256)
    verify_generated(
        "Bold Italic",
        italic_data,
        italic_zig,
        EXPECTED_ITALIC_DATA_SHA256,
        EXPECTED_ITALIC_ZIG_SHA256,
    )

    root = pathlib.Path(__file__).resolve().parents[1] / "src/render"
    (root / "fontdata.bin").write_bytes(bold_data)
    (root / "font.zig").write_text(bold_zig, encoding="utf-8")
    (root / "fontdata_italic.bin").write_bytes(italic_data)
    (root / "font_italic.zig").write_text(italic_zig, encoding="utf-8")


if __name__ == "__main__":
    main()
